// Notification types (Phase 9). VARCHAR(30) — validated here, no DB enum.
export const NotificationType = {
  APPLICATION_ACCEPTED: "APPLICATION_ACCEPTED",
  APPLICATION_REJECTED: "APPLICATION_REJECTED",
  DELIVERABLE_SUBMITTED: "DELIVERABLE_SUBMITTED",
  DELIVERABLE_APPROVED: "DELIVERABLE_APPROVED",
  DELIVERABLE_REVISION: "DELIVERABLE_REVISION",
  CONTRIBUTION_APPROVED: "CONTRIBUTION_APPROVED",
  REVIEW_RECEIVED: "REVIEW_RECEIVED",
  ARTIFACT_GENERATED: "ARTIFACT_GENERATED",
  VERIFICATION_APPROVED: "VERIFICATION_APPROVED",
  VERIFICATION_REJECTED: "VERIFICATION_REJECTED",
  PROJECT_APPROVED: "PROJECT_APPROVED",
  PROJECT_REJECTED: "PROJECT_REJECTED",
  COMPLETION_REQUESTED: "COMPLETION_REQUESTED",
  MEMBER_REMOVED: "MEMBER_REMOVED",
  SENIOR_ASSIGNED: "SENIOR_ASSIGNED",
  SENIOR_REMOVED: "SENIOR_REMOVED",
} as const;

export type NotificationTypeValue =
  (typeof NotificationType)[keyof typeof NotificationType];
